name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if release commit
        id: check_release_commit
        run: git describe --exact-match --tags $(git rev-parse HEAD)
      - uses: release-drafter/release-drafter@v5
        if: steps.check_release_commit.outcome != 'success'
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
